---
name: HTML-Accessors
version: 0.1.61
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Generate HTML elements
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::MakeMaker: 6.42
  version: 0.74
requires:
  Class::Accessor::Fast: 0.31
  HTML::GenerateUtil: 1.08
  HTML::Tagset: 3.10
  parent: 0.221
  perl: 5.008
  version: 0.74
build_requires:
  Test::More: 0.74
provides:
  HTML::Accessors:
    file: lib/HTML/Accessors.pm
    version: 0.1.61
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
