---
name: HTML-Accessors
version: 0.1.32
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Generate HTML elements
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0.31
  HTML::GenerateUtil: 1.08
  HTML::Tagset: 3.10
  NEXT: 0.60
  Readonly: 1.03
  perl: 5.8
  version: 0.74
build_requires:
  Test::More: 0.74
configure_requires:
  version: 0.74
provides:
  HTML::Accessors:
    file: lib/HTML/Accessors.pm
    version: 0.1.32
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
