---
abstract: 'Generate HTML elements'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Test::More: 0.74
configure_requires:
  Module::Build: 0.32
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Accessors
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  HTML::Accessors:
    file: lib/HTML/Accessors.pm
    version: v0.5.105
requires:
  Class::Accessor::Fast: 0.31
  HTML::GenerateUtil: 1.08
  HTML::Tagset: 3.10
  parent: 0.221
  perl: 5.008
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTML-Accessors
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: 0.5.105
