---
abstract: 'Generate HTML elements'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  Test::Requires: 0.06
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Accessors
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  HTML::Accessors:
    file: lib/HTML/Accessors.pm
    version: v0.9.1
requires:
  Class::Accessor: 0.34
  HTML::GenerateUtil: 1.10
  HTML::Tagset: 3.20
  parent: 0.224
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTML-Accessors
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.9.1
